### PR TITLE
🦊 The fox took Yiski's balls away (sanity) then fed it all of the food (dependencies) we have

### PR DESCRIPTION
**Pull request by Deftu**
So anyway, Yiski might be walking funny for a few days after this. Don't mind it, it's just healing!

(dependency fuckery, don't ask)

### CODE REVIEW

**Comment by asoji** [comment]
What **actually** happened: shadowJar nonsense, so a lot of things had to be broken apart to make this shit work, just do it can run proper in prod and such.

also `slashCommandsPackage` is removed from the Metadata format as this commit makes the Runner scan for all classes that implements Scaffold now

**Comment by asoji** [comment]
so god help me

image

**Comment by Deftu** [comment]
What god? 😃

They won't help you. 😉

**Review by asoji — COMMENTED** [review]
Looks good, should've done this before merging, my bad.

**Pull request merged**
